function withDefaults(base, extra) {
  return { ...base, ...extra };
}

function emptyBriefingExtras() {
  return {
    instAboutFocus: "",
    instUnits: "",
    instBlog: "",
    instTeamPage: "",
    instLanguages: "",
    instCertifications: "",
    instFooterContacts: "",
    instContentOwner: "",
    lpOffer: "",
    lpPromise: "",
    lpCta: "",
    lpTrafficSource: "",
    lpCampaign: "",
    lpThankYou: "",
    lpAudienceMoment: "",
    lpObjections: "",
    sysKind: "",
    sysUsers: "",
    sysModules: "",
    sysData: "",
    sysLogin: "",
    sysPermissions: "",
    sysRoles: "",
    sysReports: "",
    sysSla: "",
    sysMigration: "",
    bioMainLinks: "",
    bioHighlight: "",
    bioWhatsappText: "",
    bioPixels: "",
    bioLinkLimit: ""
  };
}

const SEEDED_TEMPLATES = [
  {
    id: "TMP-SEED-001",
    createdAt: "2026-08-01T12:00:00.000Z",
    updatedAt: "2026-09-11T18:00:00.000Z",
    serviceType: "Site institucional",
    category: "Clínicas",
    subcategory: "Clínica multidisciplinar",
    name: "Institucional Clínica Vitalle",
    sku: "TMP-INS-CLI-001",
    status: "Ativo",
    pages: "8",
    version: "1.2.0",
    url: "https://demo.fgtemplates.com/institucional-clinica-vitalle",
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1400&q=80",
    video: "https://www.youtube.com/watch?v=vitalle-demo",
    documentation: "https://docs.fgtemplates.com/institucional-clinica-vitalle",
    description: "Site institucional para clínicas, com páginas de especialidades, equipe, convênios, estrutura e agendamento. Foco em credibilidade médica e SEO local.",
    pageList: "Home, A Clínica, Especialidades, Equipe, Convênios, Estrutura, Blog, Contato",
    sections: "Hero, especialidades, corpo clínico, depoimentos, convênios, FAQ, mapa, CTA de agendamento",
    features: "WhatsApp, formulário de agendamento, blog, mapa, busca de especialidades, SEO local",
    editableFields: "logo, cores, equipe, especialidades, convênios, horários, endereço, telefone",
    technology: "HTML / CSS / JavaScript",
    hosting: "Hostinger",
    dependencies: "Swiper, Font Awesome, Google Maps",
    integrations: "WhatsApp, Google Analytics, Search Console, Meta Pixel",
    databaseRequired: "Opcional",
    databaseType: "Supabase / PostgreSQL",
    seoReady: "Preparado",
    responsive: "Sim",
    darkMode: "Não",
    performance: "Alta",
    customizationLevel: "Alta",
    basePrice: "",
    deliveryTime: "18 dias úteis",
    complexity: "Média",
    priority: "Alta",
    tags: "institucional, clinica, saude, seo local",
    internalNotes: "Bom para clínicas com 4+ especialidades e conteúdo de blog."
  },
  {
    id: "TMP-SEED-002",
    createdAt: "2026-08-02T12:00:00.000Z",
    updatedAt: "2026-09-11T18:00:00.000Z",
    serviceType: "Site institucional",
    category: "Construtoras",
    subcategory: "Incorporadora residencial",
    name: "Institucional Construtora Horizonte",
    sku: "TMP-INS-CON-001",
    status: "Ativo",
    pages: "9",
    version: "1.1.0",
    url: "https://demo.fgtemplates.com/institucional-construtora-horizonte",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1400&q=80",
    video: "https://www.youtube.com/watch?v=horizonte-demo",
    documentation: "https://docs.fgtemplates.com/institucional-construtora-horizonte",
    description: "Site institucional para construtoras e incorporadoras, com portfólio de obras, memorial descritivo, status de obra e captação de leads para lançamentos.",
    pageList: "Home, A Empresa, Empreendimentos, Obras entregues, Sustentabilidade, Blog, Carreiras, Contato",
    sections: "Hero de lançamento, números, empreendimentos, linha do tempo, diferenciais, FAQ, CTA",
    features: "Catálogo de imóveis, filtros, WhatsApp, formulário de proposta, galeria 360, blog",
    editableFields: "logo, empreendimentos, plantas, tabela de vendas, endereço, CRECI, textos",
    technology: "Next.js",
    hosting: "Vercel",
    dependencies: "Tailwind, Swiper, Lightbox",
    integrations: "WhatsApp, RD Station, Google Analytics, Meta Pixel",
    databaseRequired: "Sim",
    databaseType: "Supabase / PostgreSQL",
    seoReady: "Preparado",
    responsive: "Sim",
    darkMode: "Não",
    performance: "Alta",
    customizationLevel: "Alta",
    basePrice: "",
    deliveryTime: "25 dias úteis",
    complexity: "Alta",
    priority: "Alta",
    tags: "institucional, construtora, imoveis, lancamento",
    internalNotes: "Exige galeria pesada e atenção a performance das plantas."
  },
  {
    id: "TMP-SEED-003",
    createdAt: "2026-08-03T12:00:00.000Z",
    updatedAt: "2026-09-11T18:00:00.000Z",
    serviceType: "Site institucional",
    category: "Contabilidade",
    subcategory: "Escritório contábil consultivo",
    name: "Institucional Contábil Atlas",
    sku: "TMP-INS-CONTA-001",
    status: "Ativo",
    pages: "7",
    version: "1.0.4",
    url: "https://demo.fgtemplates.com/institucional-contabil-atlas",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1400&q=80",
    video: "https://www.youtube.com/watch?v=atlas-demo",
    documentation: "https://docs.fgtemplates.com/institucional-contabil-atlas",
    description: "Site institucional para escritórios contábeis, com serviços por regime tributário, área do cliente, autoridade técnica e captação de empresas.",
    pageList: "Home, O Escritório, Serviços, Para empresas, Blog, Carreira, Contato",
    sections: "Hero, serviços, para quem serve, depoimentos B2B, equipe, FAQ, CTA de diagnóstico",
    features: "WhatsApp, formulário de diagnóstico, blog, área do cliente, calculadora simples, SEO",
    editableFields: "logo, serviços, CRC, equipe, depoimentos, horários, cidade",
    technology: "WordPress",
    hosting: "Hostinger",
    dependencies: "Elementor, Yoast SEO",
    integrations: "WhatsApp, RD Station, Google Analytics, Search Console",
    databaseRequired: "Sim",
    databaseType: "MySQL",
    seoReady: "Preparado",
    responsive: "Sim",
    darkMode: "Não",
    performance: "Média",
    customizationLevel: "Alta",
    basePrice: "",
    deliveryTime: "16 dias úteis",
    complexity: "Média",
    priority: "Normal",
    tags: "institucional, contabilidade, b2b, consultivo",
    internalNotes: "Ótimo para conteúdo de reforma tributária e captação inbound."
  },
  {
    id: "TMP-SEED-004",
    createdAt: "2026-08-04T12:00:00.000Z",
    updatedAt: "2026-09-11T18:00:00.000Z",
    serviceType: "Landing page",
    category: "Advocacia",
    subcategory: "Trabalhista",
    name: "Landing Page Advogado Trabalhista",
    sku: "TMP-LP-ADV-001",
    status: "Ativo",
    pages: "1",
    version: "2.0.1",
    url: "https://demo.fgtemplates.com/lp-advogado-trabalhista",
    image: "https://images.unsplash.com/photo-1589829545858-04a4ce2d1a4e?auto=format&fit=crop&w=1400&q=80",
    video: "https://www.youtube.com/watch?v=lp-trabalhista-demo",
    documentation: "https://docs.fgtemplates.com/lp-advogado-trabalhista",
    description: "Landing page de alta conversão para captação de causas trabalhistas, com prova social, FAQ jurídico e CTA direto para WhatsApp.",
    pageList: "Landing única + página de obrigado",
    sections: "Hero com CTA, dores, como funciona, autoridade, depoimentos, FAQ, formulário",
    features: "WhatsApp flutuante, formulário de triagem, UTMs, pixel, prova social, FAQ",
    editableFields: "headline, oferta, depoimentos, OAB, telefone, cores, foto do advogado",
    technology: "HTML / CSS / JavaScript",
    hosting: "Vercel",
    dependencies: "Nenhum framework pesado",
    integrations: "WhatsApp, Meta Pixel, Google Ads, GA4",
    databaseRequired: "Não",
    databaseType: "",
    seoReady: "Parcial",
    responsive: "Sim",
    darkMode: "Não",
    performance: "Alta",
    customizationLevel: "Média",
    basePrice: "",
    deliveryTime: "7 dias úteis",
    complexity: "Baixa",
    priority: "Alta",
    tags: "landing, advocacia, trabalhista, conversao",
    internalNotes: "Usar com campanhas de tráfego pago. Headline deve ser reescrita por nicho."
  },
  {
    id: "TMP-SEED-005",
    createdAt: "2026-08-05T12:00:00.000Z",
    updatedAt: "2026-09-11T18:00:00.000Z",
    serviceType: "Landing page",
    category: "Academias",
    subcategory: "Aula experimental",
    name: "Landing Page Academia Prime",
    sku: "TMP-LP-ACA-001",
    status: "Ativo",
    pages: "1",
    version: "1.3.0",
    url: "https://demo.fgtemplates.com/lp-academia-prime",
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1400&q=80",
    video: "https://www.youtube.com/watch?v=lp-academia-demo",
    documentation: "https://docs.fgtemplates.com/lp-academia-prime",
    description: "Landing page para agendar aula experimental, com planos, transformações e prova de estrutura da academia.",
    pageList: "Landing única + obrigado",
    sections: "Hero com vídeo, benefícios, planos, resultados, tour, FAQ, CTA de experimental",
    features: "Agendamento, WhatsApp, countdown de vagas, pixel, depoimentos com foto",
    editableFields: "planos, horários, fotos, vídeo, CTA, unidades, preço da experimental",
    technology: "HTML / CSS / JavaScript",
    hosting: "Vercel",
    dependencies: "Swiper",
    integrations: "WhatsApp, Calendly, Meta Pixel, GA4, Asaas",
    databaseRequired: "Opcional",
    databaseType: "Planilha / Make",
    seoReady: "Parcial",
    responsive: "Sim",
    darkMode: "Sim",
    performance: "Alta",
    customizationLevel: "Média",
    basePrice: "",
    deliveryTime: "6 dias úteis",
    complexity: "Baixa",
    priority: "Urgente",
    tags: "landing, academia, experimental, conversao",
    internalNotes: "CTA sempre visível no mobile. Evitar estoque de academia genérica."
  },
  {
    id: "TMP-SEED-006",
    createdAt: "2026-08-06T12:00:00.000Z",
    updatedAt: "2026-09-11T18:00:00.000Z",
    serviceType: "Landing page",
    category: "Imobiliárias",
    subcategory: "Captação de comprador",
    name: "Landing Page Imobiliária Prime View",
    sku: "TMP-LP-IMO-001",
    status: "Ativo",
    pages: "1",
    version: "1.0.2",
    url: "https://demo.fgtemplates.com/lp-imobiliaria-prime-view",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1400&q=80",
    video: "https://www.youtube.com/watch?v=lp-imobiliaria-demo",
    documentation: "https://docs.fgtemplates.com/lp-imobiliaria-prime-view",
    description: "Landing page para lançamentos imobiliários, com galeria, planta, tabela e captura de lead qualificado.",
    pageList: "Landing do empreendimento + obrigado",
    sections: "Hero do lançamento, plantas, diferenciais, localização, tabela, tour, formulário",
    features: "Formulário de proposta, WhatsApp, galeria, mapa, UTMs, CRM",
    editableFields: "empreendimento, plantas, preço a partir de, CRECI, fotos, CTA",
    technology: "React",
    hosting: "Vercel",
    dependencies: "Lightbox, Maps",
    integrations: "WhatsApp, Kommo, Meta Pixel, GA4",
    databaseRequired: "Opcional",
    databaseType: "Supabase",
    seoReady: "Parcial",
    responsive: "Sim",
    darkMode: "Não",
    performance: "Alta",
    customizationLevel: "Média",
    basePrice: "",
    deliveryTime: "8 dias úteis",
    complexity: "Média",
    priority: "Alta",
    tags: "landing, imobiliaria, lancamento, lead",
    internalNotes: "Tabela de valores costuma mudar: deixar campo fácil de editar."
  },
  {
    id: "TMP-SEED-007",
    createdAt: "2026-08-07T12:00:00.000Z",
    updatedAt: "2026-09-11T18:00:00.000Z",
    serviceType: "Sistema",
    category: "Estética",
    subcategory: "Agenda e caixa",
    name: "Sistema de Agendamento BeautyOS",
    sku: "TMP-SYS-EST-001",
    status: "Ativo",
    pages: "12",
    version: "1.4.0",
    url: "https://demo.fgtemplates.com/sistema-beautyos",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=1400&q=80",
    video: "https://www.youtube.com/watch?v=beautyos-demo",
    documentation: "https://docs.fgtemplates.com/sistema-beautyos",
    description: "Sistema para clínicas de estética e salões, com agenda, profissionais, comissão, caixa e confirmação no WhatsApp.",
    pageList: "Login, Agenda, Clientes, Serviços, Profissionais, Financeiro, Relatórios, Configurações, Perfil do cliente",
    sections: "Dashboard, calendário, ficha do cliente, comissão, caixa do dia, confirmações",
    features: "Login, permissões, agenda, WhatsApp, relatórios, caixa, cadastro de serviços, app do cliente",
    editableFields: "logo, serviços, profissionais, horários, comissões, mensagens de WhatsApp",
    technology: "Next.js",
    hosting: "Vercel",
    dependencies: "Tailwind, FullCalendar",
    integrations: "WhatsApp, Mercado Pago, Make, Supabase",
    databaseRequired: "Sim",
    databaseType: "Supabase / PostgreSQL",
    seoReady: "Não preparado",
    responsive: "Sim",
    darkMode: "Sim",
    performance: "Alta",
    customizationLevel: "Alta",
    basePrice: "",
    deliveryTime: "35 dias úteis",
    complexity: "Alta",
    priority: "Alta",
    tags: "sistema, agenda, estetica, whatsapp",
    internalNotes: "Escopo de comissão precisa ser fechado antes do kickoff."
  },
  {
    id: "TMP-SEED-008",
    createdAt: "2026-08-08T12:00:00.000Z",
    updatedAt: "2026-09-11T18:00:00.000Z",
    serviceType: "Sistema",
    category: "Escolas",
    subcategory: "Área do aluno e responsável",
    name: "Sistema Área do Aluno EduFlow",
    sku: "TMP-SYS-EDU-001",
    status: "Ativo",
    pages: "14",
    version: "1.1.5",
    url: "https://demo.fgtemplates.com/sistema-eduflow",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1400&q=80",
    video: "https://www.youtube.com/watch?v=eduflow-demo",
    documentation: "https://docs.fgtemplates.com/sistema-eduflow",
    description: "Sistema escolar com área do aluno, boletim, recados, financeiro e painel da secretaria.",
    pageList: "Login, Painel secretaria, Turmas, Alunos, Notas, Financeiro, Recados, Área do responsável, Relatórios",
    sections: "Dashboard pedagógico, lista de turmas, boletim, mensalidades, comunicados",
    features: "Login, papéis, boletim, recados, boletos, relatórios, importação de planilha",
    editableFields: "logo da escola, séries, mensagens, taxas, responsáveis, calendário letivo",
    technology: "Laravel",
    hosting: "VPS",
    dependencies: "Bootstrap, Chart.js",
    integrations: "E-mail, WhatsApp, gateway de boleto, Google Workspace",
    databaseRequired: "Sim",
    databaseType: "MySQL",
    seoReady: "Não preparado",
    responsive: "Sim",
    darkMode: "Não",
    performance: "Média",
    customizationLevel: "Alta",
    basePrice: "",
    deliveryTime: "45 dias úteis",
    complexity: "Alta",
    priority: "Normal",
    tags: "sistema, escola, boletim, area do aluno",
    internalNotes: "LGPD e permissão de responsável precisam estar no contrato."
  },
  {
    id: "TMP-SEED-009",
    createdAt: "2026-08-09T12:00:00.000Z",
    updatedAt: "2026-09-11T18:00:00.000Z",
    serviceType: "Sistema",
    category: "Delivery",
    subcategory: "Pedidos e cozinha",
    name: "Sistema Delivery RotaChef",
    sku: "TMP-SYS-DEL-001",
    status: "Ativo",
    pages: "10",
    version: "1.0.8",
    url: "https://demo.fgtemplates.com/sistema-rotachef",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1400&q=80",
    video: "https://www.youtube.com/watch?v=rotachef-demo",
    documentation: "https://docs.fgtemplates.com/sistema-rotachef",
    description: "Sistema de pedidos para restaurantes e dark kitchens, com cardápio, cozinha, entregadores e caixa.",
    pageList: "Cardápio público, Checkout, Painel pedidos, Cozinha, Entregadores, Cardápio admin, Relatórios, Configurações",
    sections: "Kanban de pedidos, cardápio, status de entrega, caixa do dia, desempenho",
    features: "Cardápio, checkout, status ao vivo, entregador, Mercado Pago, relatórios, WhatsApp",
    editableFields: "logo, cardápio, taxas, áreas de entrega, horários, formas de pagamento",
    technology: "React",
    hosting: "Vercel",
    dependencies: "Tailwind, Socket status",
    integrations: "Mercado Pago, WhatsApp, Google Maps, Make",
    databaseRequired: "Sim",
    databaseType: "Supabase / PostgreSQL",
    seoReady: "Parcial",
    responsive: "Sim",
    darkMode: "Sim",
    performance: "Alta",
    customizationLevel: "Alta",
    basePrice: "",
    deliveryTime: "30 dias úteis",
    complexity: "Alta",
    priority: "Alta",
    tags: "sistema, delivery, restaurante, pedidos",
    internalNotes: "Definir se haverá app do entregador no MVP ou só painel web."
  },
  {
    id: "TMP-SEED-010",
    createdAt: "2026-08-10T12:00:00.000Z",
    updatedAt: "2026-09-11T18:00:00.000Z",
    serviceType: "Link na bio",
    category: "Agências de Marketing",
    subcategory: "Página de links",
    name: "Link na Bio SocialPulse",
    sku: "TMP-BIO-MKT-001",
    status: "Ativo",
    pages: "1",
    version: "1.2.2",
    url: "https://demo.fgtemplates.com/link-bio-socialpulse",
    image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=1400&q=80",
    video: "https://www.youtube.com/watch?v=linkbio-demo",
    documentation: "https://docs.fgtemplates.com/link-bio-socialpulse",
    description: "Página de link na bio com botões, destaque de oferta, pixels e redirecionamento para WhatsApp, catálogo e agendamento.",
    pageList: "Página única de links",
    sections: "Avatar, bio, destaque, grade de botões, rodapé de redes, pixel",
    features: "Botões ilimitados configuráveis, UTMs, WhatsApp, pixel, destaque animado",
    editableFields: "foto, nome, bio, botões, cores, oferta em destaque, WhatsApp",
    technology: "HTML / CSS / JavaScript",
    hosting: "Vercel",
    dependencies: "Nenhum",
    integrations: "WhatsApp, Meta Pixel, GA4, UTMs",
    databaseRequired: "Não",
    databaseType: "",
    seoReady: "Não preparado",
    responsive: "Sim",
    darkMode: "Opcional",
    performance: "Alta",
    customizationLevel: "Baixa",
    basePrice: "",
    deliveryTime: "3 dias úteis",
    complexity: "Baixa",
    priority: "Normal",
    tags: "link na bio, instagram, captura, whatsapp",
    internalNotes: "Entrega rápida. Ideal como porta de entrada para LP ou institucional."
  }
];

function companySeed(data) {
  return withDefaults({
    stateRegistration: "Isento",
    municipalRegistration: "100000",
    companyType: "LTDA",
    size: "Pequeno",
    country: "Brasil",
    hasBrandGuide: "Não",
    hasWebsite: "Desatualizado",
    hasDomain: "Sim",
    contractType: "Projeto único",
    priority: "Normal",
    paymentMethod: "Pix",
    youtube: "",
    complement: "",
    logoUrl: ""
  }, data);
}

const SEED_COMPANIES = [
  companySeed({
    id: "EMP-SEED-001",
    createdAt: "2026-08-20T12:00:00.000Z",
    updatedAt: "2026-09-11T18:20:00.000Z",
    legalName: "Mendes Rocha Advogados Associados Ltda",
    tradeName: "Mendes & Rocha Advocacia Trabalhista",
    document: "28.441.902/0001-55",
    stateRegistration: "Isento",
    municipalRegistration: "184422",
    companyType: "LTDA",
    size: "Pequeno",
    foundationYear: "2014",
    segment: "Advocacia",
    niche: "Direito do Trabalho",
    status: "Cliente",
    responsibleName: "Ana Paula Mendes",
    responsibleRole: "Sócia fundadora",
    whatsapp: "47999881234",
    phone: "4733631100",
    email: "ana.mendes@mendesrocha.adv.br",
    financeEmail: "financeiro@mendesrocha.adv.br",
    website: "https://www.mendesrocha.adv.br",
    instagram: "@mendesrocha.adv",
    linkedin: "linkedin.com/company/mendes-rocha",
    facebook: "facebook.com/mendesrocha.adv",
    youtube: "youtube.com/@mendesrocha",
    zip: "88330-000",
    city: "Balneário Camboriú",
    state: "SC",
    street: "Avenida Brasil",
    number: "1450",
    complement: "Sala 804",
    neighborhood: "Centro",
    about: "Escritório especializado em direito do trabalho, com 12 anos de atuação no Litoral Norte de Santa Catarina.",
    products: "Reclamações trabalhistas, defesa patronal, consultoria preventiva e auditoria de RH.",
    audience: "Empresas de médio porte e profissionais CLT da região.",
    region: "Balneário Camboriú, Itajaí, Itapema e Navegantes",
    differentials: "Atendimento humanizado, respostas rápidas e honorários transparentes.",
    competitors: "Escritórios generalistas da região e portais de advocacia online.",
    employees: "9",
    monthlyRevenue: "R$ 92.000",
    averageTicket: "R$ 4.800,00",
    salesChannel: "WhatsApp e indicação",
    hasBrandGuide: "Sim",
    primaryColor: "#0E2A4A",
    secondaryColor: "#C9A227",
    communicationTone: "Corporativo",
    visualStyle: "Premium, corporativo e sóbrio",
    accountManager: "Felipe",
    contractType: "Projeto + retainer",
    priority: "Alta",
    monthlyFee: "R$ 6.900,00",
    paymentMethod: "Pix e boleto",
    startDate: "2026-09-15",
    hasWebsite: "Desatualizado",
    hasDomain: "Sim",
    hosting: "Hostinger",
    crm: "RD Station",
    currentTools: "WhatsApp Business, RD Station, Google Workspace",
    automations: "Lead do site para CRM e WhatsApp interno.",
    tags: "advocacia, trabalhista, premium, litoral",
    commercialNotes: "Alta chance de retainer de conteúdo jurídico.",
    internalNotes: "Textos jurídicos ainda parciais."
  }),
  companySeed({
    id: "EMP-SEED-002",
    createdAt: "2026-08-28T10:00:00.000Z",
    updatedAt: "2026-09-11T18:21:00.000Z",
    legalName: "Prime Fit Performance Treinamento Físico Ltda",
    tradeName: "Prime Fit Performance",
    document: "41.208.773/0001-19",
    stateRegistration: "255.901.332",
    municipalRegistration: "99821",
    size: "Médio",
    foundationYear: "2020",
    segment: "Academias",
    niche: "Academia boutique",
    status: "Cliente",
    responsibleName: "Lucas Ferreira da Silva",
    responsibleRole: "CEO",
    whatsapp: "47991224567",
    phone: "4732449088",
    email: "lucas@primefitperformance.com.br",
    financeEmail: "financeiro@primefitperformance.com.br",
    website: "https://primefitperformance.com.br",
    instagram: "@primefit.ita",
    linkedin: "linkedin.com/company/primefit",
    facebook: "facebook.com/primefititajai",
    youtube: "youtube.com/@primefitperformance",
    zip: "88301-000",
    city: "Itajaí",
    state: "SC",
    street: "Rua Brusque",
    number: "890",
    neighborhood: "Centro",
    about: "Academia boutique com foco em treino personalizado, emagrecimento e performance.",
    products: "Musculação, personal, funcional, avaliação física e planos corporativos.",
    audience: "Adultos de 25 a 45 anos que buscam resultado com acompanhamento.",
    region: "Itajaí, Balneário Camboriú e Camboriú",
    differentials: "Turmas reduzidas, app de evolução e professores fixos.",
    competitors: "Smart Fit, Bio Ritmo e estúdios de personal.",
    employees: "18",
    monthlyRevenue: "R$ 140.000",
    averageTicket: "R$ 289,00 / mês",
    salesChannel: "Instagram e visita à unidade",
    primaryColor: "#111111",
    secondaryColor: "#E8FF3D",
    communicationTone: "Premium",
    visualStyle: "Esportivo premium e energético",
    accountManager: "Felipe",
    priority: "Urgente",
    monthlyFee: "R$ 5.400,00",
    paymentMethod: "Cartão e Pix",
    startDate: "2026-09-12",
    hosting: "A contratar",
    crm: "Kommo",
    currentTools: "Instagram, WhatsApp, Asaas, Calendly",
    automations: "Experimental com confirmação no WhatsApp.",
    tags: "academia, premium, itajai, experimental",
    commercialNotes: "Unidade 2 inaugura em outubro.",
    internalNotes: "Pedir autorização de imagem dos alunos."
  }),
  companySeed({
    id: "EMP-SEED-003",
    createdAt: "2026-09-01T15:00:00.000Z",
    updatedAt: "2026-09-11T18:22:00.000Z",
    legalName: "Litoral Prime Transfer Transporte Executivo Ltda",
    tradeName: "Litoral Prime Transfer",
    document: "33.917.640/0001-08",
    stateRegistration: "261.440.118",
    municipalRegistration: "44012",
    foundationYear: "2018",
    segment: "Transporte Executivo",
    niche: "Transfer aeroportuário",
    status: "Prospect",
    responsibleName: "Camila Souza Ribeiro",
    responsibleRole: "Diretora comercial",
    whatsapp: "47988550123",
    phone: "4733487700",
    email: "camila@litoralprimetransfer.com.br",
    financeEmail: "financeiro@litoralprimetransfer.com.br",
    website: "https://litoralprimetransfer.com.br",
    instagram: "@litoralprimetransfer",
    linkedin: "linkedin.com/company/litoral-prime-transfer",
    facebook: "facebook.com/litoralprimetransfer",
    zip: "88370-000",
    city: "Navegantes",
    state: "SC",
    street: "Avenida Prefeito Osvaldo Reis",
    number: "2100",
    complement: "Box 12",
    neighborhood: "São Domingos",
    about: "Transporte executivo e transfers aeroportuários com frota rastreada e atendimento 24h.",
    products: "Transfer aeroporto, motorista particular, receptivo e contratos corporativos.",
    audience: "Executivos, hotéis, agências e famílias em temporada.",
    region: "Navegantes, Itajaí, Balneário Camboriú e Vale do Itajaí",
    differentials: "Frota rastreada, motoristas treinados e orçamento rápido.",
    competitors: "Uber Black, 99 Comfort e transfers locais.",
    employees: "11",
    monthlyRevenue: "R$ 78.000",
    averageTicket: "R$ 320,00 por corrida",
    salesChannel: "WhatsApp e parcerias com hotéis",
    primaryColor: "#1456D9",
    secondaryColor: "#0E213C",
    communicationTone: "Direto e comercial",
    visualStyle: "Tecnológico e executivo",
    accountManager: "Felipe",
    contractType: "Ainda não definido",
    monthlyFee: "R$ 4.800,00",
    paymentMethod: "Mercado Pago",
    startDate: "2026-09-18",
    hasDomain: "Não",
    hosting: "A contratar",
    crm: "Google Sheets + Make",
    currentTools: "WhatsApp, Mercado Pago, Google Meu Negócio",
    automations: "Orçamento para planilha e WhatsApp da operação.",
    tags: "transfer, executivo, aeroporto, navegantes",
    commercialNotes: "Três hotéis podem virar case na home.",
    internalNotes: "Aguardar logo final antes da home."
  }),
  companySeed({
    id: "EMP-SEED-004",
    createdAt: "2026-07-12T09:00:00.000Z",
    updatedAt: "2026-09-10T11:00:00.000Z",
    legalName: "Clínica Vitalle Saúde Integrada Ltda",
    tradeName: "Clínica Vitalle",
    document: "17.552.301/0001-44",
    municipalRegistration: "33210",
    foundationYear: "2011",
    segment: "Clínicas",
    niche: "Multidisciplinar",
    status: "Cliente",
    responsibleName: "Dra. Helena Duarte",
    responsibleRole: "Diretora clínica",
    whatsapp: "47984001122",
    phone: "4732268800",
    email: "helena@clinicavitalle.com.br",
    financeEmail: "financeiro@clinicavitalle.com.br",
    website: "https://www.clinicavitalle.com.br",
    instagram: "@clinicavitalle",
    linkedin: "linkedin.com/company/clinica-vitalle",
    facebook: "facebook.com/clinicavitalle",
    youtube: "youtube.com/@clinicavitalle",
    zip: "88015-100",
    city: "Florianópolis",
    state: "SC",
    street: "Rua Esteves Júnior",
    number: "605",
    complement: "2º andar",
    neighborhood: "Centro",
    about: "Clínica multidisciplinar com cardiologia, endocrinologia, nutrição e check-up executivo.",
    products: "Consultas, check-up, exames de rotina e programas de acompanhamento.",
    audience: "Famílias e executivos de 30 a 60 anos.",
    region: "Grande Florianópolis",
    differentials: "Equipe fixa, laudos rápidos e atendimento humanizado.",
    competitors: "Clínicas de rua e operadoras com rede própria.",
    employees: "27",
    monthlyRevenue: "R$ 210.000",
    averageTicket: "R$ 380,00",
    salesChannel: "Indicação médica e Google",
    hasBrandGuide: "Sim",
    primaryColor: "#0F766E",
    secondaryColor: "#134E4A",
    communicationTone: "Próximo e humano",
    visualStyle: "Clean, clínico e acolhedor",
    accountManager: "Marina",
    contractType: "Projeto + retainer",
    priority: "Alta",
    monthlyFee: "R$ 8.200,00",
    startDate: "2026-08-01",
    hosting: "Hostinger",
    crm: "Clinicorp",
    currentTools: "WhatsApp, Clinicorp, Google Meu Negócio",
    automations: "Confirmação de consulta e nps pós-atendimento.",
    tags: "clinica, florianopolis, institucional, saude",
    commercialNotes: "Quer ranquear para check-up em Floripa.",
    internalNotes: "CRM atual não exporta bem. Planejar integração."
  }),
  companySeed({
    id: "EMP-SEED-005",
    createdAt: "2026-06-18T09:00:00.000Z",
    updatedAt: "2026-09-09T11:00:00.000Z",
    legalName: "Horizonte Incorporações Spe Ltda",
    tradeName: "Construtora Horizonte",
    document: "09.774.210/0001-81",
    stateRegistration: "214.009.551",
    municipalRegistration: "12044",
    size: "Grande",
    foundationYear: "2006",
    segment: "Construtoras",
    niche: "Residencial médio-alto padrão",
    status: "Prospect",
    responsibleName: "Roberto Lima",
    responsibleRole: "Diretor comercial",
    whatsapp: "47993004411",
    phone: "4730334500",
    email: "roberto@construtorahorizonte.com.br",
    financeEmail: "financeiro@construtorahorizonte.com.br",
    website: "https://www.construtorahorizonte.com.br",
    instagram: "@construtorahorizonte",
    linkedin: "linkedin.com/company/horizonte-incorporacoes",
    facebook: "facebook.com/construtorahorizonte",
    zip: "89010-000",
    city: "Blumenau",
    state: "SC",
    street: "Rua 15 de Novembro",
    number: "1120",
    neighborhood: "Centro",
    about: "Incorporadora com 18 anos de mercado e 32 empreendimentos entregues no Vale do Itajaí.",
    products: "Apartamentos, studios e lançamentos com memorial descritivo.",
    audience: "Famílias e investidores locais.",
    region: "Blumenau, Pomerode e Gaspar",
    differentials: "Obra com cronograma público e pós-entrega estruturado.",
    competitors: "Incorporadoras regionais e nacionais de médio padrão.",
    employees: "64",
    monthlyRevenue: "R$ 1.800.000",
    averageTicket: "R$ 620.000",
    salesChannel: "Plantão de vendas e corretores parceiros",
    hasBrandGuide: "Sim",
    primaryColor: "#9A3412",
    secondaryColor: "#1C1917",
    communicationTone: "Corporativo",
    visualStyle: "Sóbrio, arquitetônico e premium",
    accountManager: "Felipe",
    contractType: "Projeto único",
    priority: "Alta",
    monthlyFee: "R$ 11.000,00",
    startDate: "2026-09-20",
    hosting: "AWS",
    crm: "Vista Soft",
    currentTools: "Vista, WhatsApp, Meta Ads",
    automations: "Lead de lançamento para CRM e plantão.",
    tags: "construtora, blumenau, lancamento, institucional",
    commercialNotes: "Lançamento em outubro precisa de LP e institucional.",
    internalNotes: "Banco de fotos das obras está desorganizado."
  }),
  companySeed({
    id: "EMP-SEED-006",
    createdAt: "2026-05-04T09:00:00.000Z",
    updatedAt: "2026-09-08T11:00:00.000Z",
    legalName: "Atlas Contabilidade Consultiva Ltda",
    tradeName: "Contábil Atlas",
    document: "22.109.448/0001-07",
    municipalRegistration: "55410",
    foundationYear: "2009",
    segment: "Contabilidade",
    niche: "Consultivo para PMEs",
    status: "Ativa",
    responsibleName: "Patrícia Gomes",
    responsibleRole: "Sócia",
    whatsapp: "47997770012",
    phone: "4733221199",
    email: "patricia@contabilatlas.com.br",
    financeEmail: "financeiro@contabilatlas.com.br",
    website: "https://www.contabilatlas.com.br",
    instagram: "@contabilatlas",
    linkedin: "linkedin.com/company/contabil-atlas",
    facebook: "facebook.com/contabilatlas",
    zip: "89201-000",
    city: "Joinville",
    state: "SC",
    street: "Rua do Príncipe",
    number: "300",
    complement: "Sala 502",
    neighborhood: "Centro",
    about: "Escritório contábil consultivo para indústrias e comércios de Joinville, com foco em BPO financeiro.",
    products: "Contabilidade, fiscal, folha, BPO e diagnóstico tributário.",
    audience: "PMEs industriais e comércio varejista.",
    region: "Joinville e Norte de SC",
    differentials: "Reunião mensal de resultados e dashboard financeiro.",
    competitors: "Escritórios tradicionais do centro e franquias contábeis.",
    employees: "22",
    monthlyRevenue: "R$ 165.000",
    averageTicket: "R$ 1.450,00",
    salesChannel: "LinkedIn e indicação de advogados",
    hasBrandGuide: "Não",
    primaryColor: "#1E3A8A",
    secondaryColor: "#0F172A",
    communicationTone: "Técnico",
    visualStyle: "Corporativo e limpo",
    accountManager: "Marina",
    monthlyFee: "R$ 5.100,00",
    startDate: "2026-09-25",
    hosting: "Hostinger",
    crm: "RD Station",
    currentTools: "Domínio Sistemas, WhatsApp, RD",
    automations: "Diagnóstico tributário vira card no RD.",
    tags: "contabilidade, joinville, b2b, institucional",
    commercialNotes: "Quer blog técnico para inbound.",
    internalNotes: "CRC e dados da equipe prontos."
  }),
  companySeed({
    id: "EMP-SEED-007",
    createdAt: "2026-04-22T09:00:00.000Z",
    updatedAt: "2026-09-07T11:00:00.000Z",
    legalName: "Prime View Negócios Imobiliários Ltda",
    tradeName: "Imobiliária Prime View",
    document: "31.220.905/0001-60",
    municipalRegistration: "67102",
    foundationYear: "2016",
    segment: "Imobiliárias",
    niche: "Alto padrão no litoral",
    status: "Cliente",
    responsibleName: "Eduardo Martins",
    responsibleRole: "Gestor comercial",
    whatsapp: "47988887766",
    phone: "4733642020",
    email: "eduardo@primeviewimoveis.com.br",
    financeEmail: "financeiro@primeviewimoveis.com.br",
    website: "https://www.primeviewimoveis.com.br",
    instagram: "@primeviewimoveis",
    linkedin: "linkedin.com/company/prime-view",
    facebook: "facebook.com/primeviewimoveis",
    zip: "88330-101",
    city: "Balneário Camboriú",
    state: "SC",
    street: "Avenida Atlântica",
    number: "4010",
    complement: "Loja 02",
    neighborhood: "Centro",
    about: "Imobiliária de alto padrão com foco em apartamentos frente mar e lançamentos.",
    products: "Venda, locação e lançamentos de alto padrão.",
    audience: "Investidores e famílias de alto poder aquisitivo.",
    region: "Balneário Camboriú, Itapema e Piçarras",
    differentials: "Tour guiado, corretores bilingues e após-venda.",
    competitors: "Lopes, Habitec e imobiliárias de rua da Atlântica.",
    employees: "16",
    monthlyRevenue: "R$ 420.000",
    averageTicket: "R$ 1.900.000",
    salesChannel: "Instagram e portais",
    hasBrandGuide: "Sim",
    primaryColor: "#B45309",
    secondaryColor: "#111827",
    communicationTone: "Premium",
    visualStyle: "Luxo discreto, fotos grandes e pouco texto",
    accountManager: "Felipe",
    priority: "Urgente",
    monthlyFee: "R$ 3.800,00",
    startDate: "2026-09-14",
    hosting: "Vercel",
    crm: "Vista Soft",
    currentTools: "Vista, Instagram Ads, WhatsApp",
    automations: "Lead da LP vai para o plantão em 1 minuto.",
    tags: "imobiliaria, landing, alto padrao, bc",
    commercialNotes: "Campanha de lançamento na Barra Sul.",
    internalNotes: "CRECI e tabela atualizados."
  }),
  companySeed({
    id: "EMP-SEED-008",
    createdAt: "2026-03-11T09:00:00.000Z",
    updatedAt: "2026-09-06T11:00:00.000Z",
    legalName: "Studio Luna Estética Avançada Ltda",
    tradeName: "Studio Luna Estética",
    document: "45.882.119/0001-33",
    municipalRegistration: "80911",
    companyType: "SLU",
    foundationYear: "2019",
    segment: "Estética",
    niche: "Estética facial e corporal",
    status: "Cliente",
    responsibleName: "Luna Carvalho",
    responsibleRole: "Proprietária",
    whatsapp: "47991002345",
    phone: "4733990011",
    email: "luna@studiolunaestetica.com.br",
    financeEmail: "financeiro@studiolunaestetica.com.br",
    website: "https://www.studiolunaestetica.com.br",
    instagram: "@studioluna.estetica",
    linkedin: "",
    facebook: "facebook.com/studiolunaestetica",
    youtube: "youtube.com/@studioluna",
    zip: "88330-220",
    city: "Balneário Camboriú",
    state: "SC",
    street: "Rua 1500",
    number: "220",
    neighborhood: "Centro",
    about: "Clínica de estética com protocolos de pele, corpo e bem-estar, 4 cabines e 6 profissionais.",
    products: "Limpeza de pele, Harmonização, drenagem, pacotes mensais.",
    audience: "Mulheres 25 a 50 anos da região.",
    region: "Balneário Camboriú e Itajaí",
    differentials: "Protocolos assinados e acompanhamento fotográfico.",
    competitors: "Franquias de estética e clínicas de rua.",
    employees: "8",
    monthlyRevenue: "R$ 96.000",
    averageTicket: "R$ 340,00",
    salesChannel: "Instagram",
    primaryColor: "#BE185D",
    secondaryColor: "#4A044E",
    communicationTone: "Próximo e humano",
    visualStyle: "Delicado, claro e sofisticado",
    accountManager: "Marina",
    contractType: "Mensalidade",
    priority: "Alta",
    monthlyFee: "R$ 1.890,00",
    paymentMethod: "Cartão e Pix",
    startDate: "2026-08-20",
    hosting: "Vercel",
    crm: "Trinks",
    currentTools: "Trinks, Instagram, WhatsApp",
    automations: "Confirmação de agenda e aniversário da cliente.",
    tags: "estetica, sistema, agenda, bc",
    commercialNotes: "Dor principal: agenda duplicada e no-show.",
    internalNotes: "Migrar da planilha do Trinks no go-live."
  }),
  companySeed({
    id: "EMP-SEED-009",
    createdAt: "2026-02-02T09:00:00.000Z",
    updatedAt: "2026-09-05T11:00:00.000Z",
    legalName: "Colégio Bosque Norte Educação Ltda",
    tradeName: "Colégio Bosque Norte",
    document: "05.441.778/0001-90",
    municipalRegistration: "2230",
    size: "Médio",
    foundationYear: "1998",
    segment: "Escolas",
    niche: "Educação básica particular",
    status: "Prospect",
    responsibleName: "Sérgio Almeida",
    responsibleRole: "Diretor geral",
    whatsapp: "47981112233",
    phone: "4730327000",
    email: "sergio@colegiobosquenorte.com.br",
    financeEmail: "financeiro@colegiobosquenorte.com.br",
    website: "https://www.colegiobosquenorte.com.br",
    instagram: "@colegiobosquenorte",
    linkedin: "linkedin.com/school/colegio-bosque-norte",
    facebook: "facebook.com/colegiobosquenorte",
    youtube: "youtube.com/@bosquenorte",
    zip: "89050-000",
    city: "Blumenau",
    state: "SC",
    street: "Rua São Paulo",
    number: "2450",
    neighborhood: "Itoupava Seca",
    about: "Colégio particular com educação infantil ao ensino médio, 780 alunos e forte comunicação com famílias.",
    products: "Mensalidades, material, atividades extras e reforço.",
    audience: "Famílias da classe média de Blumenau.",
    region: "Blumenau",
    differentials: "Acompanhamento pedagógico e comunicação diária com responsáveis.",
    competitors: "Colégios confessionais e redes particulares da cidade.",
    employees: "92",
    monthlyRevenue: "R$ 980.000",
    averageTicket: "R$ 1.280,00",
    salesChannel: "Indicação de pais e visitas agendadas",
    hasBrandGuide: "Sim",
    primaryColor: "#166534",
    secondaryColor: "#14532D",
    communicationTone: "Próximo e humano",
    visualStyle: "Acolhedor, escolar e organizado",
    accountManager: "Marina",
    contractType: "Projeto + retainer",
    monthlyFee: "R$ 19.500,00",
    startDate: "2026-10-01",
    hosting: "VPS",
    crm: "Planilha interna",
    currentTools: "Google Classroom, WhatsApp, boleto bancário",
    automations: "Recado da secretaria e lembrete de mensalidade.",
    tags: "escola, sistema, blumenau, area do aluno",
    commercialNotes: "Trocar o grupo de WhatsApp da turma por um sistema.",
    internalNotes: "Dados de alunos em Excel. Prever migração."
  }),
  companySeed({
    id: "EMP-SEED-010",
    createdAt: "2026-01-15T09:00:00.000Z",
    updatedAt: "2026-09-04T11:00:00.000Z",
    legalName: "RotaChef Cozinha e Delivery Ltda",
    tradeName: "RotaChef Delivery",
    document: "48.330.217/0001-12",
    municipalRegistration: "99002",
    companyType: "ME",
    foundationYear: "2021",
    segment: "Delivery",
    niche: "Dark kitchen de marmitas e lanches",
    status: "Ativa",
    responsibleName: "Thiago Nunes",
    responsibleRole: "Sócio-operador",
    whatsapp: "47992003456",
    phone: "4733456677",
    email: "thiago@rotachef.com.br",
    financeEmail: "financeiro@rotachef.com.br",
    website: "https://www.rotachef.com.br",
    instagram: "@rotachef.delivery",
    linkedin: "",
    facebook: "facebook.com/rotachefdelivery",
    youtube: "",
    zip: "88301-402",
    city: "Itajaí",
    state: "SC",
    street: "Rua Samuel Heusi",
    number: "540",
    neighborhood: "Centro",
    about: "Dark kitchen com cardápio de marmitas fit, burgers e combos para empresas no centro de Itajaí.",
    products: "Marmitas, lanches, combos empresariais e assinatura semanal.",
    audience: "Escritórios e moradores do centro.",
    region: "Itajaí centro e Braga",
    differentials: "Entrega em 35 minutos e cardápio rotativo.",
    competitors: "iFood de redes e marmitarias locais.",
    employees: "14",
    monthlyRevenue: "R$ 88.000",
    averageTicket: "R$ 42,00",
    salesChannel: "iFood, Instagram e WhatsApp",
    primaryColor: "#DC2626",
    secondaryColor: "#111827",
    communicationTone: "Direto e comercial",
    visualStyle: "Apetitoso, rápido e urbano",
    accountManager: "Felipe",
    contractType: "Mensalidade",
    priority: "Urgente",
    monthlyFee: "R$ 2.400,00",
    paymentMethod: "Mercado Pago",
    startDate: "2026-09-16",
    hasDomain: "Sim",
    hosting: "Vercel",
    crm: "Nenhum",
    currentTools: "iFood, WhatsApp, planilha de pedidos",
    automations: "Pedido pago vira ticket na cozinha.",
    tags: "delivery, sistema, itajai, cardapio",
    commercialNotes: "Quer sair da dependência do iFood.",
    internalNotes: "Cardápio muda toda segunda. Precisa ser fácil de editar."
  })
];

function briefingSeed(data) {
  return withDefaults({
    responsibleRole: "",
    document: "",
    city: "",
    state: "",
    currentWebsite: "",
    instagram: "",
    targetAudience: "",
    serviceRegion: "",
    customerProblem: "",
    differentials: "",
    competitors: "",
    averageTicket: "",
    mainSalesChannel: "",
    primaryConversion: "",
    projectGoalMetric: "",
    currentWebsiteProblems: "",
    hasLogo: "Sim",
    hasBrandGuide: "Não",
    hasFonts: "Não",
    primaryColor: "",
    secondaryColor: "",
    avoidColor: "",
    visualStyle: "",
    desiredFeeling: "",
    references: "",
    dislikedReferences: "",
    homeSections: "",
    features: "",
    hasTexts: "Não",
    hasPhotos: "Não",
    hasVideos: "Não",
    pendingAssets: "",
    seoCity: "",
    seoState: "",
    keywords: "",
    faqQuestions: "",
    communicationTone: "",
    domain: "",
    hasDomain: "Não",
    hasHosting: "Não",
    hostingProvider: "",
    accessNotes: "",
    socialNetworks: "",
    integrations: "",
    automationsWanted: "",
    crm: "",
    paymentPlatform: "",
    deadline: "",
    budget: "",
    projectPriority: "Normal",
    startDate: "",
    deliveryDate: "",
    projectApprover: "",
    clientNotes: "",
    internalNotes: "",
    ...emptyBriefingExtras()
  }, data);
}

const SEEDED_BRIEFINGS = [
  briefingSeed({
    id: "BRF-SEED-001",
    companyId: "EMP-SEED-001",
    createdAt: "2026-09-02T13:20:00.000Z",
    updatedAt: "2026-09-11T18:20:00.000Z",
    companyName: "Mendes & Rocha Advocacia Trabalhista",
    responsibleName: "Ana Paula Mendes",
    responsibleRole: "Sócia fundadora",
    whatsapp: "47999881234",
    email: "ana.mendes@mendesrocha.adv.br",
    document: "28.441.902/0001-55",
    city: "Balneário Camboriú",
    state: "SC",
    currentWebsite: "https://www.mendesrocha.adv.br",
    instagram: "@mendesrocha.adv",
    aboutCompany: "Escritório especializado em direito do trabalho, com 12 anos de atuação no Litoral Norte de Santa Catarina.",
    services: "Reclamações trabalhistas, defesa patronal, consultoria preventiva, auditoria de rotinas de RH.",
    targetAudience: "Empresas de médio porte e profissionais CLT da região.",
    serviceRegion: "Balneário Camboriú, Itajaí, Itapema e Navegantes",
    customerProblem: "Falta de segurança jurídica e dificuldade para encontrar um escritório especializado e claro.",
    differentials: "Atendimento humanizado, respostas em até 4 horas úteis e honorários transparentes.",
    competitors: "Escritórios generalistas da região e portais de advocacia online.",
    averageTicket: "R$ 4.800,00",
    mainSalesChannel: "WhatsApp e indicação",
    websiteGoal: "Gerar solicitações de atendimento pelo WhatsApp e transmitir credibilidade jurídica.",
    primaryConversion: "Enviar mensagem no WhatsApp",
    projectGoalMetric: "40 leads qualificados por mês",
    currentWebsiteProblems: "Visual datado, sem prova social e formulário que não chega no WhatsApp.",
    hasLogo: "Sim",
    hasBrandGuide: "Sim",
    hasFonts: "Sim",
    primaryColor: "#0E2A4A",
    secondaryColor: "#C9A227",
    avoidColor: "Vermelho vibrante",
    visualStyle: "Premium, corporativo e sóbrio",
    desiredFeeling: "Confiança, autoridade e proximidade.",
    references: "https://www.machadomeyer.com.br — organização das áreas.",
    dislikedReferences: "Martelo 3D e foto de estoque de advogado.",
    serviceType: "Landing page",
    chosenTemplate: "Landing Page Advogado Trabalhista",
    pagesWanted: "Landing de captação trabalhista e página de obrigado.",
    homeSections: "Hero, dores, autoridade, depoimentos, FAQ e CTA.",
    features: "WhatsApp, formulário de triagem, pixel e UTMs.",
    hasTexts: "Parcialmente",
    hasPhotos: "Sim",
    hasVideos: "Parcialmente",
    pendingAssets: "Logo SVG, fotos da sócia e 6 depoimentos.",
    seoCity: "Balneário Camboriú",
    seoState: "Santa Catarina",
    keywords: "advogado trabalhista em Balneário Camboriú, reclamação trabalhista",
    faqQuestions: "Quanto custa uma consulta? Atendem trabalhador e empresa?",
    communicationTone: "Corporativo",
    domain: "www.mendesrocha.adv.br",
    hasDomain: "Sim",
    hasHosting: "Sim",
    hostingProvider: "Hostinger",
    accessNotes: "Acessos com a sócia Ana Paula.",
    socialNetworks: "Instagram, LinkedIn, Facebook",
    integrations: "GA4, Search Console, Meta Pixel, WhatsApp, RD Station",
    automationsWanted: "Lead para RD Station e WhatsApp interno.",
    crm: "RD Station",
    paymentPlatform: "Não utiliza checkout no site",
    deadline: "18 dias úteis",
    budget: "R$ 6.900,00",
    projectPriority: "Alta",
    startDate: "2026-09-15",
    deliveryDate: "2026-10-10",
    projectApprover: "Ana Paula Mendes — sócia fundadora",
    clientNotes: "Não usar a palavra barato. Destacar atendimento para empresas.",
    internalNotes: "Campanha de tráfego já está no ar em rascunho.",
    lpOffer: "Avaliação trabalhista inicial com retorno em 24 horas úteis.",
    lpPromise: "Entender se a causa é viável sem juridiquês e com próximo passo claro.",
    lpCta: "Falar com a advogada agora",
    lpTrafficSource: "Google Ads e Instagram",
    lpCampaign: "Trabalhista Litoral Setembro",
    lpThankYou: "Página /obrigado + mensagem automática no WhatsApp",
    lpAudienceMoment: "Público quente, já pesquisando reclamação trabalhista.",
    lpObjections: "Medo de custo, demora do processo e se o escritório é especializado."
  }),
  briefingSeed({
    id: "BRF-SEED-002",
    companyId: "EMP-SEED-004",
    createdAt: "2026-09-04T10:05:00.000Z",
    updatedAt: "2026-09-11T18:21:00.000Z",
    companyName: "Clínica Vitalle",
    responsibleName: "Dra. Helena Duarte",
    responsibleRole: "Diretora clínica",
    whatsapp: "47984001122",
    email: "helena@clinicavitalle.com.br",
    document: "17.552.301/0001-44",
    city: "Florianópolis",
    state: "SC",
    currentWebsite: "https://www.clinicavitalle.com.br",
    instagram: "@clinicavitalle",
    aboutCompany: "Clínica multidisciplinar com cardiologia, endocrinologia, nutrição e check-up executivo.",
    services: "Consultas, check-up, exames de rotina e programas de acompanhamento.",
    targetAudience: "Famílias e executivos de 30 a 60 anos.",
    serviceRegion: "Grande Florianópolis",
    customerProblem: "Dificuldade de encontrar uma clínica completa, com equipe fixa e agendamento simples.",
    differentials: "Equipe fixa, laudos rápidos e atendimento humanizado.",
    competitors: "Clínicas de rua e operadoras com rede própria.",
    averageTicket: "R$ 380,00",
    mainSalesChannel: "Indicação médica e Google",
    websiteGoal: "Transmitir credibilidade institucional e gerar agendamentos de check-up e consultas.",
    primaryConversion: "Agendar atendimento",
    projectGoalMetric: "70 agendamentos orgânicos por mês",
    currentWebsiteProblems: "Não mostra o corpo clínico, lento e sem blog de autoridade.",
    hasLogo: "Sim",
    hasBrandGuide: "Sim",
    hasFonts: "Sim",
    primaryColor: "#0F766E",
    secondaryColor: "#134E4A",
    avoidColor: "Vermelho hospitalar",
    visualStyle: "Clean, clínico e acolhedor",
    desiredFeeling: "Cuidado, ciência e tranquilidade.",
    references: "Sites de hospitais premium com equipe em destaque.",
    dislikedReferences: "Estoque de estetoscópio e banners rotativos.",
    serviceType: "Site institucional",
    chosenTemplate: "Institucional Clínica Vitalle",
    pagesWanted: "Home, A Clínica, Especialidades, Equipe, Convênios, Estrutura, Blog, Contato",
    homeSections: "Hero, especialidades, equipe, depoimentos, convênios, FAQ, mapa",
    features: "WhatsApp, agendamento, blog, mapa, SEO local",
    hasTexts: "Parcialmente",
    hasPhotos: "Sim",
    hasVideos: "Não",
    pendingAssets: "Fotos da equipe, lista de convênios e biografias.",
    seoCity: "Florianópolis",
    seoState: "Santa Catarina",
    keywords: "clínica em Florianópolis, check-up executivo, endocrinologista Floripa",
    faqQuestions: "Quais convênios atendem? Como agendar check-up?",
    communicationTone: "Próximo e humano",
    domain: "www.clinicavitalle.com.br",
    hasDomain: "Sim",
    hasHosting: "Sim",
    hostingProvider: "Hostinger",
    accessNotes: "Acessos com a diretora Helena.",
    socialNetworks: "Instagram, Facebook, YouTube, Google Meu Negócio",
    integrations: "GA4, WhatsApp, Clinicorp, Search Console",
    automationsWanted: "Confirmação de consulta e NPS.",
    crm: "Clinicorp",
    paymentPlatform: "Não usa checkout",
    deadline: "20 dias",
    budget: "R$ 8.200,00",
    projectPriority: "Alta",
    startDate: "2026-08-01",
    deliveryDate: "2026-09-30",
    projectApprover: "Dra. Helena Duarte",
    clientNotes: "Equipe precisa aparecer com CRM e especialidade.",
    internalNotes: "Priorizar SEO local e página de check-up.",
    instAboutFocus: "História da clínica, propósito de cuidado contínuo e segurança dos protocolos.",
    instUnits: "1 unidade no Centro de Florianópolis",
    instBlog: "Sim",
    instTeamPage: "Sim",
    instLanguages: "Português",
    instCertifications: "CRM-SC, selos de qualidade internos e parcerias laboratoriais",
    instFooterContacts: "CNPJ, endereço, horários, WhatsApp, políticas de privacidade",
    instContentOwner: "Dra. Helena Duarte — diretora clínica"
  }),
  briefingSeed({
    id: "BRF-SEED-003",
    companyId: "EMP-SEED-008",
    createdAt: "2026-09-08T16:40:00.000Z",
    updatedAt: "2026-09-11T18:22:00.000Z",
    companyName: "Studio Luna Estética",
    responsibleName: "Luna Carvalho",
    responsibleRole: "Proprietária",
    whatsapp: "47991002345",
    email: "luna@studiolunaestetica.com.br",
    document: "45.882.119/0001-33",
    city: "Balneário Camboriú",
    state: "SC",
    currentWebsite: "https://www.studiolunaestetica.com.br",
    instagram: "@studioluna.estetica",
    aboutCompany: "Clínica de estética com protocolos de pele, corpo e bem-estar, 4 cabines e 6 profissionais.",
    services: "Limpeza de pele, Harmonização, drenagem, pacotes mensais.",
    targetAudience: "Mulheres 25 a 50 anos da região.",
    serviceRegion: "Balneário Camboriú e Itajaí",
    customerProblem: "Agenda desorganizada, no-show alto e confirmação manual no WhatsApp.",
    differentials: "Protocolos assinados e acompanhamento fotográfico.",
    competitors: "Franquias de estética e clínicas de rua.",
    averageTicket: "R$ 340,00",
    mainSalesChannel: "Instagram",
    websiteGoal: "Operar a clínica em um sistema de agenda, caixa e confirmação automática.",
    primaryConversion: "Agendar atendimento",
    projectGoalMetric: "Reduzir no-show em 40% e centralizar a agenda",
    currentWebsiteProblems: "Site cartão de visitas. A operação vive no WhatsApp e no Trinks paralelo.",
    hasLogo: "Sim",
    hasBrandGuide: "Não",
    hasFonts: "Não",
    primaryColor: "#BE185D",
    secondaryColor: "#4A044E",
    avoidColor: "Dourado exagerado",
    visualStyle: "Delicado, claro e sofisticado",
    desiredFeeling: "Cuidado, organização e exclusividade.",
    references: "Sistemas de estética com calendário limpo e confirmação no WhatsApp.",
    dislikedReferences: "Painéis lotados de métricas inúteis na tela inicial.",
    serviceType: "Sistema",
    chosenTemplate: "Sistema de Agendamento BeautyOS",
    pagesWanted: "Login, agenda, clientes, serviços, profissionais, financeiro, relatórios e perfil da cliente.",
    homeSections: "Dashboard do dia, agenda, atalhos de caixa e confirmações pendentes.",
    features: "Agenda, permissões, WhatsApp, caixa, comissão, ficha da cliente.",
    hasTexts: "Parcialmente",
    hasPhotos: "Sim",
    hasVideos: "Não",
    pendingAssets: "Lista de serviços, profissionais, comissões e mensagens de confirmação.",
    seoCity: "Balneário Camboriú",
    seoState: "Santa Catarina",
    keywords: "não é o foco. Sistema interno.",
    faqQuestions: "Como remarcar? Como lançar pacote?",
    communicationTone: "Próximo e humano",
    domain: "app.studiolunaestetica.com.br",
    hasDomain: "Sim",
    hasHosting: "Não",
    hostingProvider: "A contratar na Vercel",
    accessNotes: "Luna fornece exportação do Trinks.",
    socialNetworks: "Instagram e WhatsApp",
    integrations: "WhatsApp, Mercado Pago, Make, Supabase",
    automationsWanted: "Confirmação, lembrete 24h e aniversário.",
    crm: "Trinks",
    paymentPlatform: "Mercado Pago",
    deadline: "35 dias",
    budget: "R$ 12.500,00",
    projectPriority: "Alta",
    startDate: "2026-08-20",
    deliveryDate: "2026-10-08",
    projectApprover: "Luna Carvalho",
    clientNotes: "A recepção não pode perder o horário da profissional.",
    internalNotes: "Sistema é o tipo que mais pede campos. Mapear comissão com cuidado.",
    sysKind: "Agendamento e caixa para estética",
    sysUsers: "1 admin, 1 recepção, 6 profissionais e clientes finais",
    sysModules: "Agenda, clientes, serviços, profissionais, comissão, caixa, relatórios, confirmação WhatsApp",
    sysData: "Clientes, anamnese, fotos de evolução, pacotes, comissões e caixa diário",
    sysLogin: "E-mail e senha",
    sysPermissions: "admin, recepção, profissional, cliente",
    sysRoles: "Proprietária, recepção, esteticista, cliente",
    sysReports: "Ocupação da agenda, no-show, faturamento e comissão por profissional",
    sysSla: "Agenda não pode ficar fora do ar no sábado",
    sysMigration: "Sim, sistema atual"
  })
];
