(() => {
  "use strict";
  const HOURS = { 0:[16,23], 1:[16,23], 2:[16,23], 3:[16,23], 4:[16,23], 5:[16,23], 6:[16,23] };
  const WHEN = ["no domingo","na segunda","na terça","na quarta","na quinta","na sexta","no sábado"];
  const status = document.querySelector("#status"), statusText = document.querySelector("#statusText"), toastEl = document.querySelector("#toast");
  const cards = [...document.querySelectorAll(".biz")];
  const count = document.querySelector("#count");
  let index = 0, timer;
  const nextOpening = day => { for (let s=1;s<=7;s++){ const d=(day+s)%7; if (HOURS[d]) return `abre ${s===1?"amanhã":WHEN[d]} às ${HOURS[d][0]}h`; } return "sem expediente"; };
  const describe = now => { const r=HOURS[now.getDay()], m=now.getHours()*60+now.getMinutes(); if (!r) return {open:false,text:`Fechado · ${nextOpening(now.getDay())}`}; if (m<r[0]*60) return {open:false,text:`Abre hoje às ${r[0]}h`}; if (m>=r[1]*60) return {open:false,text:`Fechado · ${nextOpening(now.getDay())}`}; return {open:true,text:`Aberto agora · até ${r[1]}h`}; };
  const render = () => { const n=describe(new Date()); if (statusText.textContent!==n.text) statusText.textContent=n.text; status.classList.toggle("is-open", n.open); };
  const toast = m => { toastEl.textContent=m; toastEl.classList.add("show"); clearTimeout(timer); timer=setTimeout(()=>toastEl.classList.remove("show"),2400); };
  const copyText = (value, success) => { const fallback=()=>{ const a=document.createElement("textarea"); a.value=value; a.style.cssText="position:fixed;left:-9999px"; document.body.append(a); a.select(); toast(document.execCommand("copy")?success:"Não foi possível copiar"); a.remove(); }; if (navigator.clipboard&&window.isSecureContext) navigator.clipboard.writeText(value).then(()=>toast(success)).catch(fallback); else fallback(); };
  const show = next => { index = (next + cards.length) % cards.length; cards.forEach((card,i)=>{ card.hidden = i!==index; }); count.textContent = `${index+1} / ${cards.length}`; };
  document.querySelector("#next").onclick = () => show(index+1);
  document.querySelector("#prev").onclick = () => show(index-1);
  document.querySelector("#copyAddress").onclick = () => copyText(document.querySelector("#copyAddress").dataset.copy, "Endereço copiado");
  document.querySelector("#share").onclick = async () => { if (navigator.share){ try { await navigator.share({title:"Cartão",url:location.href}); return; } catch(e){ if(e.name==="AbortError") return; } } copyText(location.href,"Link copiado"); };
  document.querySelector("#year").textContent = String(new Date().getFullYear());
  render(); setInterval(render, 30000);
})();
