const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={service:{name:'Tonificação',price:85,duration:'1h'},date:null,time:null,month:new Date(new Date().getFullYear(),new Date().getMonth(),1)};
const months=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
const weekdays=['domingo','segunda-feira','terça-feira','quarta-feira','quinta-feira','sexta-feira','sábado'];
const times=['09:00','10:30','13:00','14:30','16:00','17:30'];
const money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
function renderCalendar(){const y=state.month.getFullYear(),m=state.month.getMonth(),first=new Date(y,m,1),offset=(first.getDay()+6)%7,count=new Date(y,m+1,0).getDate(),today=new Date();$('#month').textContent=`${months[m]} ${y}`;const box=$('#days');box.innerHTML='';for(let i=0;i<offset;i++){const blank=document.createElement('span');blank.setAttribute('aria-hidden','true');box.append(blank)}for(let d=1;d<=count;d++){const date=new Date(y,m,d),b=document.createElement('button');b.type='button';b.textContent=d;b.setAttribute('aria-label',`${d} de ${months[m]}`);b.disabled=date<new Date(today.getFullYear(),today.getMonth(),today.getDate())||date.getDay()===0;if(date.toDateString()===today.toDateString())b.classList.add('today');if(state.date&&date.toDateString()===state.date.toDateString())b.classList.add('selected');b.addEventListener('click',()=>{state.date=date;state.time=null;renderCalendar();renderTimes();summary()});box.append(b)}}
function renderTimes(){const box=$('#slots');box.innerHTML='';times.forEach((time,i)=>{const b=document.createElement('button');b.type='button';b.textContent=time;b.disabled=!state.date||(state.date.toDateString()===new Date().toDateString()&&time<=new Date().toTimeString().slice(0,5))||(i===2&&state.date.getDate()%3===0);if(state.time===time)b.classList.add('selected');b.addEventListener('click',()=>{state.time=time;renderTimes();summary()});box.append(b)});$('#chosenDate').textContent=state.date?`${state.date.getDate()} ${months[state.date.getMonth()].toLowerCase()}`:'Selecione uma data'}
function summary(){ $('#sumService').textContent=state.service.name;$('#sumPrice').textContent=money(state.service.price);$('#sumWhen').textContent=state.date&&state.time?`${weekdays[state.date.getDay()]}, ${state.date.getDate()} de ${months[state.date.getMonth()].toLowerCase()} · ${state.time}`:state.date?`${state.date.getDate()} de ${months[state.date.getMonth()].toLowerCase()} · escolha um horário`:'Escolha uma data e um horário'}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3800)}
$$('.service').forEach(card=>card.addEventListener('click',()=>{$$('.service').forEach(x=>x.classList.remove('selected'));card.classList.add('selected');state.service={name:card.dataset.name,price:Number(card.dataset.price),duration:card.dataset.duration};summary()}));
$('#prev').addEventListener('click',()=>{const now=new Date(),prev=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);if(prev<new Date(now.getFullYear(),now.getMonth(),1))return;state.month=prev;state.date=null;state.time=null;renderCalendar();renderTimes();summary()});$('#next').addEventListener('click',()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);state.date=null;state.time=null;renderCalendar();renderTimes();summary()});
$('#phone').addEventListener('input',e=>{let v=e.target.value.replace(/\D/g,'').slice(0,11);if(v.length>10)v=v.replace(/^(\d{2})(\d{5})(\d{4}).*/,'($1) $2-$3');else if(v.length>6)v=v.replace(/^(\d{2})(\d{4})(\d{0,4}).*/,'($1) $2-$3');else if(v.length>2)v=v.replace(/^(\d{2})(\d{0,5})/,'($1) $2');else if(v.length)v='('+v;e.target.value=v});
$('#form').addEventListener('submit',e=>{e.preventDefault();if(!state.date)return toast('Escolha uma data para continuar.');if(!state.time)return toast('Agora escolha um horário disponível.');const name=$('#name').value.trim(),phone=$('#phone').value.trim();if(!name||phone.replace(/\D/g,'').length<10)return toast('Confira seu nome e número de WhatsApp.');const booking={service:state.service.name,price:state.service.price,duration:state.service.duration,date:state.date.toISOString().slice(0,10),time:state.time,name,phone,email:$('#email').value.trim(),notes:$('#notes').value.trim(),createdAt:new Date().toISOString()};const saved=JSON.parse(localStorage.getItem('floraBookings')||'[]');saved.push(booking);localStorage.setItem('floraBookings',JSON.stringify(saved));toast(`Prontinho, ${name.split(' ')[0]}! Seu pedido foi registrado neste modo de demonstração.`);$('#form').reset();state.date=null;state.time=null;renderCalendar();renderTimes();summary()});
renderCalendar();renderTimes();summary();
