(()=>{'use strict';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const st={service:null,date:null,time:null,month:new Date(),client:null},months=['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'],weekdays=['domingo','segunda-feira','terça-feira','quarta-feira','quinta-feira','sexta-feira','sábado'];
const pad=n=>String(n).padStart(2,'0'),key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,pretty=d=>`${weekdays[d.getDay()]}, ${d.getDate()} de ${months[d.getMonth()]} de ${d.getFullYear()}`,money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});let timer;
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function choose(b){$$('.service').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');st.service={name:b.dataset.name,price:+b.dataset.price,duration:b.dataset.time,icon:b.dataset.icon};$('#sumName').textContent=st.service.name;$('#sumMeta').textContent=`${st.service.duration} · ${money(st.service.price)}`;$('#next1').disabled=false}
$$('.service').forEach(b=>b.addEventListener('click',()=>choose(b)));
function step(n){for(let i=1;i<=4;i++){$(`#p${i}`).classList.toggle('hidden',i!==n);const b=$(`[data-step="${i}"]`);b.classList.toggle('active',i===n);b.classList.toggle('done',i<n)}}
$$('.steps button').forEach(b=>b.addEventListener('click',()=>{let n=+b.dataset.step;if(n===1)step(1);else if(n===2&&st.service)step(2);else if(n===3&&st.date&&st.time)step(3);else if(n===4&&st.client){review();step(4)}else toast('Complete as etapas anteriores para continuar.')}));
$('#edit').onclick=()=>step(1);$('#next1').onclick=()=>{step(2);calendar()};$('#to1').onclick=$('#back1').onclick=()=>step(1);$('#back2').onclick=()=>step(2);$('#back3').onclick=()=>step(3);
$('#prev').onclick=()=>{let now=new Date();now.setHours(0,0,0,0);let p=new Date(st.month.getFullYear(),st.month.getMonth()-1,1);if(p>=new Date(now.getFullYear(),now.getMonth(),1))st.month=p;else toast('Não há datas anteriores disponíveis.');calendar()};
$('#next').onclick=()=>{st.month=new Date(st.month.getFullYear(),st.month.getMonth()+1,1);calendar()};
function calendar(){let y=st.month.getFullYear(),m=st.month.getMonth(),offset=(new Date(y,m,1).getDay()+6)%7,total=new Date(y,m+1,0).getDate();$('#month').textContent=months[m][0].toUpperCase()+months[m].slice(1)+' '+y;let box=$('#days');box.innerHTML='';for(let i=0;i<offset;i++)box.append(document.createElement('span'));let today=new Date();today.setHours(0,0,0,0);for(let n=1;n<=total;n++){let d=new Date(y,m,n);d.setHours(0,0,0,0);let b=document.createElement('button');b.textContent=n;b.type='button';b.disabled=d<today||d.getDay()===0;if(!b.disabled)b.classList.add('available');if(key(d)===key(today))b.classList.add('today');if(st.date&&key(d)===key(st.date))b.classList.add('selected');b.onclick=()=>{st.date=d;st.time=null;calendar();slots();$('#next2').disabled=true};box.append(b)}}
function slots(){if(!st.date){$('#dateLabel').textContent='Escolha uma data';$('#slots').innerHTML='<p>Selecione um dia no calendário.</p>';$('#duration').textContent=st.service?.duration||'—';return}$('#dateLabel').textContent=`${st.date.getDate()} de ${months[st.date.getMonth()]}`;$('#duration').textContent=st.service.duration;let all=['09:00','09:40','10:20','11:00','11:40','13:00','13:40','14:20','15:00','15:40','16:20','17:00'],seed=st.date.getDate()+st.date.getMonth(),times=all.filter((_,i)=>(i+seed)%5!==0),box=$('#slots');box.innerHTML='';times.forEach(t=>{let b=document.createElement('button');b.type='button';b.textContent=t;b.classList.toggle('selected',st.time===t);b.onclick=()=>{st.time=t;slots();$('#next2').disabled=false};box.append(b)})}
$('#next2').onclick=()=>{if(st.date&&st.time)step(3)};
$('#phone').oninput=e=>{let v=e.target.value.replace(/\D/g,'').slice(0,11);if(v.length>10)v=v.replace(/^(\d{2})(\d{5})(\d{0,4}).*/,'($1) $2-$3');else if(v.length>6)v=v.replace(/^(\d{2})(\d{4})(\d{0,4}).*/,'($1) $2-$3');else if(v.length>2)v=v.replace(/^(\d{2})(\d{0,5})/,'($1) $2');else if(v)v='('+v;e.target.value=v};
$('#form').onsubmit=e=>{e.preventDefault();let name=$('#name').value.trim(),phone=$('#phone').value.trim();if(name.length<2){toast('Informe seu nome.');return}if(phone.replace(/\D/g,'').length<10){toast('Informe um WhatsApp válido.');return}st.client={name,phone,email:$('#email').value.trim(),note:$('#note').value.trim()};review();step(4)};
function review(){$('#rIcon').textContent=st.service.icon;$('#rService').textContent=st.service.name;$('#rDuration').textContent=st.service.duration;$('#rDate').textContent=pretty(st.date);$('#rTime').textContent=st.time;$('#rName').textContent=st.client.name;$('#rPhone').textContent=st.client.phone;$('#rPrice').textContent=money(st.service.price);$('#emailRow').classList.toggle('hidden',!st.client.email);$('#rEmail').textContent=st.client.email;$('#noteRow').classList.toggle('hidden',!st.client.note);$('#rNote').textContent=st.client.note}
$('#editService').onclick=()=>step(1);
$('#finish').onclick=async()=>{let btn=$('#finish');btn.disabled=true;btn.textContent='Enviando…';let payload={service:st.service.name,price:st.service.price,duration:st.service.duration,date:key(st.date),time:st.time,client:st.client,source:'amora-studio-booking',createdAt:new Date().toISOString()},WEBHOOK_URL='';try{if(WEBHOOK_URL){let r=await fetch(WEBHOOK_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw Error()}else{let k='amora-demo-bookings',a=JSON.parse(localStorage.getItem(k)||'[]');a.push(payload);localStorage.setItem(k,JSON.stringify(a))}$('#firstName').textContent=st.client.name.split(/\s+/)[0];$('#successDate').textContent=pretty(st.date)+' · '+st.time;$('#successService').textContent=st.service.name;$('#successText').textContent=WEBHOOK_URL?'Sua solicitação foi enviada ao studio. Nossa equipe poderá entrar em contato para confirmar.':'Solicitação registrada neste navegador em modo demonstração. Conecte o webhook para receber reservas no seu sistema.';$('#p4').classList.add('hidden');$('#success').classList.remove('hidden');$$('.steps button').forEach(b=>{b.classList.remove('active');b.classList.add('done')})}catch(e){toast('Não foi possível enviar. Tente novamente.')}finally{btn.disabled=false;btn.innerHTML='Enviar solicitação <b>✓</b>'}};
$('#again').onclick=()=>{st.date=st.time=st.client=null;st.month=new Date();$('#form').reset();$('#success').classList.add('hidden');$('#p1').classList.remove('hidden');step(1);$('#next2').disabled=true;calendar();slots();window.scrollTo({top:0,behavior:'smooth'})};
function help(){toast('Você escolhe o dia e a hora. A confirmação segue pelo WhatsApp.')}$('#help').onclick=help;$('#year').textContent=new Date().getFullYear();choose($('.service.selected'));calendar();slots();
})();