const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const titles=[['O que vamos fazer?','Escolha seu serviço favorito.'],['Qual dia fica bom?','Encontre uma data e um horário disponíveis.'],['Quem vem se cuidar?','Só precisamos de algumas informações.'],['Tudo pronto, flor?','Confira os detalhes antes de confirmar.']];
const state={step:1,date:null,time:null,month:new Date(new Date().getFullYear(),new Date().getMonth(),1)};
const months=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
function service(){let r=$('input[name="service"]:checked');return{name:r.value,price:+r.dataset.price,duration:r.dataset.duration}}
function money(n){return n.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})}
function showStep(n){state.step=n;$$('.step-panel').forEach(p=>p.classList.toggle('active',+p.dataset.step===n));$('#stepKicker').textContent=`PASSO 0${n} DE 04` ;$('#stepTitle').textContent=titles[n-1][0];$('#stepDescription').textContent=titles[n-1][1];$('#stepNumber').textContent=`0${n}`;$('#progressBar').style.width=`${n*25}%`;$('#backButton').hidden=n===1;$('#nextButton').hidden=n===4;$('#submitButton').hidden=n!==4;$('#formError').textContent='';if(n===2)renderCalendar();if(n===4)fillReview()}
function renderCalendar(){let y=state.month.getFullYear(),m=state.month.getMonth(),now=new Date(),grid=$('#calendarGrid');$('#monthLabel').textContent=`${months[m]} ${y}`;grid.innerHTML='';let offset=(new Date(y,m,1).getDay()+6)%7,total=new Date(y,m+1,0).getDate();for(let i=0;i<offset;i++)grid.append(document.createElement('span'));for(let d=1;d<=total;d++){let date=new Date(y,m,d),b=document.createElement('button');b.type='button';b.textContent=d;b.disabled=date<new Date(now.getFullYear(),now.getMonth(),now.getDate())||date.getDay()===0;if(date.toDateString()===now.toDateString())b.classList.add('today');if(state.date&&date.toDateString()===state.date.toDateString())b.classList.add('selected');b.onclick=()=>{state.date=date;state.time=null;renderCalendar();renderTimes()};grid.append(b)}$('#prevMonth').disabled=y===now.getFullYear()&&m<=now.getMonth()}
function renderTimes(){let box=$('#timeOptions');box.innerHTML='';$('#selectedDateLabel').textContent=state.date?`${state.date.getDate()} de ${months[state.date.getMonth()]}`:'Selecione uma data acima';if(!state.date){box.innerHTML='<p class="empty">Os horários aparecem depois que você escolher o dia.</p>';return}['09:00','09:30','10:00','10:30','11:00','11:30','13:00','13:30','14:00','14:30','15:00','15:30','16:00','16:30','17:00','17:30'].forEach((t,i)=>{let b=document.createElement('button');b.type='button';b.textContent=t;let now=new Date(),past=state.date.toDateString()===now.toDateString()&&t<=`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`;b.disabled=past||(state.date.getDate()+i)%13===0;if(state.time===t)b.classList.add('selected');b.onclick=()=>{state.time=t;renderTimes()};box.append(b)})}
function fillReview(){let s=service();$('#reviewService').textContent=s.name;$('#reviewPrice').textContent=money(s.price);$('#reviewDate').textContent=state.date?`${String(state.date.getDate()).padStart(2,'0')}/${String(state.date.getMonth()+1).padStart(2,'0')}/${state.date.getFullYear()}`:'—';$('#reviewTime').textContent=state.time||'—';$('#reviewName').textContent=$('#clientName').value.trim()||'—'}
function err(s){$('#formError').textContent=s}
function valid(){if(state.step===1)return true;if(state.step===2){if(!state.date)return err('Escolha uma data para continuar.'),false;if(!state.time)return err('Agora selecione um horário.'),false;return true}if(state.step===3){if($('#clientName').value.trim().length<2)return err('Informe seu nome completo.'),false;if($('#clientPhone').value.replace(/\D/g,'').length<10)return err('Confira seu número de WhatsApp.'),false;let e=$('#clientEmail').value.trim();if(e&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e))return err('Confira o e-mail informado.'),false;return true}return true}
$$('.service').forEach(l=>l.onclick=()=>{$$('.service').forEach(x=>x.classList.remove('selected'));l.classList.add('selected');l.querySelector('input').checked=true});
$('#nextButton').onclick=()=>{if(valid())showStep(Math.min(4,state.step+1))};$('#backButton').onclick=()=>showStep(Math.max(1,state.step-1));
$('#prevMonth').onclick=()=>{let n=new Date(),p=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);if(p<new Date(n.getFullYear(),n.getMonth(),1))return;state.month=p;state.date=null;state.time=null;renderCalendar();renderTimes()};
$('#nextMonth').onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);state.date=null;state.time=null;renderCalendar();renderTimes()};
$('#clientPhone').oninput=e=>{let v=e.target.value.replace(/\D/g,'').slice(0,11);if(v.length>10)v=v.replace(/^(\d{2})(\d{5})(\d{4})$/,'($1) $2-$3');else if(v.length>6)v=v.replace(/^(\d{2})(\d{4})(\d{0,4})$/,'($1) $2-$3');else if(v.length>2)v=v.replace(/^(\d{2})(\d{0,5})$/,'($1) $2');else if(v)v=`(${v}`;e.target.value=v};
$('#bookingForm').onsubmit=e=>{e.preventDefault();if(!valid())return;let s=service(),b={service:s.name,price:s.price,duration:s.duration,date:`${state.date.getFullYear()}-${String(state.date.getMonth()+1).padStart(2,'0')}-${String(state.date.getDate()).padStart(2,'0')}`,time:state.time,name:$('#clientName').value.trim(),phone:$('#clientPhone').value.trim(),email:$('#clientEmail').value.trim(),notes:$('#clientNotes').value.trim(),createdAt:new Date().toISOString()};let all=JSON.parse(localStorage.getItem('floraBookings')||'[]');all.push(b);localStorage.setItem('floraBookings',JSON.stringify(all));let t=$('#toast');t.textContent=`Solicitação registrada, ${b.name.split(' ')[0]}! Modo de demonstração.`;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),4500);$('#bookingForm').reset();state.date=null;state.time=null;state.month=new Date(new Date().getFullYear(),new Date().getMonth(),1);$$('.service').forEach((x,i)=>x.classList.toggle('selected',i===0));renderCalendar();renderTimes();showStep(1)};
$('#year').textContent=new Date().getFullYear();renderCalendar();renderTimes();