(() => {
"use strict";
// Configure aqui a URL do webhook para receber agendamentos reais.
const WEBHOOK_URL = "";
const form=document.querySelector("#booking-form"), steps=[...document.querySelectorAll(".form-step")], indicators=[...document.querySelectorAll("[data-ind]")], services=[...document.querySelectorAll(".service")], dateInput=document.querySelector("#date"), slots=[...document.querySelectorAll("[data-time]")], submit=document.querySelector("#submit"), toast=document.querySelector("#toast");
let step=1,time="",toastTimer;
const selected=()=>{const i=form.querySelector('[name="service"]:checked');return i?{name:i.value,price:+i.dataset.price,duration:+i.dataset.duration}:null};
const digits=s=>s.replace(/\D/g,""), money=n=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(n);
const error=(id,msg)=>document.querySelector("#"+id).textContent=msg;
const clear=()=>document.querySelectorAll(".error").forEach(e=>e.textContent="");
const notify=msg=>{toast.textContent=msg;toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),3000)};
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const today=new Date();dateInput.min=iso(today);
function go(n){step=n;steps.forEach(s=>s.classList.toggle("active",+s.dataset.step===n));indicators.forEach(el=>{let i=+el.dataset.ind;el.classList.toggle("active",i===n);el.classList.toggle("done",i<n);el.querySelector("i").textContent=i<n?"✓":String(i).padStart(2,"0")});document.querySelector("#step-kicker").textContent=`PASSO ${n} DE 4`;document.querySelector("#counter").innerHTML=`${String(n).padStart(2,"0")} <i>/ 04</i>`;document.querySelector("#progress").style.width=n*25+"%";document.querySelector("#step-title").textContent=["Escolha seu ritual","Encontre seu horário","Conte sobre você","Confira sua solicitação"][n-1];clear()}
services.forEach(s=>s.addEventListener("click",()=>{s.querySelector("input").checked=true;services.forEach(x=>x.classList.toggle("selected",x===s))}));
dateInput.addEventListener("change",()=>{time="";slots.forEach(b=>b.classList.remove("selected"));if(!dateInput.value)return;const d=new Date(dateInput.value+"T12:00:00");if(d<new Date(iso(today)+"T00:00:00")){dateInput.value="";notify("Escolha uma data a partir de hoje.")}else if(d.getDay()===0){dateInput.value="";notify("Não atendemos aos domingos. Escolha outra data.")}});
slots.forEach(b=>b.addEventListener("click",()=>{if(!dateInput.value){error("date-error","Selecione a data antes do horário.");dateInput.focus();return}slots.forEach(x=>x.classList.toggle("selected",x===b));time=b.dataset.time;error("date-error","")}));
function validate(n){clear();if(n===1&&!selected()){error("service-error","Escolha um serviço para continuar.");return false}if(n===2){if(!dateInput.value){error("date-error","Selecione a data do atendimento.");dateInput.focus();return false}if(!time){error("date-error","Selecione um horário disponível.");return false}if(new Date(dateInput.value+"T12:00:00").getDay()===0){error("date-error","Escolha um dia diferente de domingo.");return false}}if(n===3){let name=form.elements.name.value.trim(),phone=digits(form.elements.phone.value),email=form.elements.email.value.trim();if(name.length<3){error("data-error","Informe seu nome completo.");form.elements.name.focus();return false}if(phone.length<10||phone.length>11){error("data-error","Informe um WhatsApp válido com DDD.");form.elements.phone.focus();return false}if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){error("data-error","Confira o e-mail informado.");form.elements.email.focus();return false}fillReview()}return true}
document.querySelectorAll(".next").forEach(b=>b.addEventListener("click",()=>{if(validate(step))go(Math.min(4,step+1))}));document.querySelectorAll(".back").forEach(b=>b.addEventListener("click",()=>go(Math.max(1,step-1))));
function dateLabel(v){return v?new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"2-digit",month:"long",year:"numeric"}).format(new Date(v+"T12:00:00")):"—"}
function fillReview(){const s=selected();document.querySelector("#r-service").textContent=`${s.name} · ${s.duration} min`;document.querySelector("#r-date").textContent=dateLabel(dateInput.value);document.querySelector("#r-time").textContent=time;document.querySelector("#r-name").textContent=form.elements.name.value.trim();document.querySelector("#r-phone").textContent=form.elements.phone.value;document.querySelector("#r-price").textContent=money(s.price)}
form.elements.phone.addEventListener("input",e=>{let d=digits(e.target.value).slice(0,11);if(d.length>10)d=d.replace(/^(\d{2})(\d{5})(\d{0,4})$/,"($1) $2-$3");else if(d.length>6)d=d.replace(/^(\d{2})(\d{4})(\d{0,4})$/,"($1) $2-$3");else if(d.length>2)d=d.replace(/^(\d{2})(\d+)/,"($1) $2");else if(d.length)d="("+d;e.target.value=d});
function payload(){const s=selected();return{id:"LUNA-"+Date.now().toString().slice(-8),service:s.name,price:s.price,duration_minutes:s.duration,date:dateInput.value,time,customer:{name:form.elements.name.value.trim(),phone:form.elements.phone.value.trim(),email:form.elements.email.value.trim(),notes:form.elements.notes.value.trim()},created_at:new Date().toISOString(),source:"Plantão"}}
form.addEventListener("submit",async e=>{e.preventDefault();if(step!==4)return;if(!document.querySelector("#consent").checked){error("review-error","Marque a confirmação para enviar.");return}const data=payload();submit.disabled=true;submit.textContent="Enviando...";try{if(WEBHOOK_URL){const r=await fetch(WEBHOOK_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});if(!r.ok)throw Error("Falha ao enviar a solicitação.")}else{const k="luna_atelier_demo_bookings",list=JSON.parse(localStorage.getItem(k)||"[]");list.push(data);localStorage.setItem(k,JSON.stringify(list))}steps.forEach(s=>s.classList.remove("active"));document.querySelector("#success").hidden=false;document.querySelector("#reference").textContent="Código da solicitação: "+data.id;document.querySelector(".top").hidden=true;document.querySelector(".progress").hidden=true;indicators.forEach(i=>i.classList.add("done"));document.querySelector("#agendar").scrollIntoView({behavior:"smooth",block:"start"})}catch(err){error("review-error","Não foi possível enviar. Confira a conexão e tente novamente.");notify(err.message||"Erro ao enviar.")}finally{submit.disabled=false;submit.innerHTML='Enviar solicitação <span>♡</span>'}});
document.querySelector("#restart").addEventListener("click",()=>{form.reset();time="";slots.forEach(b=>b.classList.remove("selected"));services.forEach(s=>s.classList.toggle("selected",s.querySelector("input").checked));document.querySelector("#success").hidden=true;document.querySelector(".top").hidden=false;document.querySelector(".progress").hidden=false;go(1);document.querySelector("#agendar").scrollIntoView({behavior:"smooth",block:"start"})});
go(1);
})();