const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={service:{name:'Protocolo',price:45,duration:'45 min',description:'Cuidado completo para suas mãos'},date:null,time:null,month:new Date(new Date().getFullYear(),new Date().getMonth(),1)};
const months=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
const week=['domingo','segunda-feira','terça-feira','quarta-feira','quinta-feira','sexta-feira','sábado'];
const slots={morning:['09:00','09:45','10:30','11:15'],afternoon:['13:00','14:00','15:00','16:00','17:00']};
const money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const same=(a,b)=>!!a&&!!b&&a.toDateString()===b.toDateString();
function renderCalendar(){let y=state.month.getFullYear(),m=state.month.getMonth(),today=new Date(),grid=$('#calendarDays');$('#monthLabel').textContent=`${months[m]} ${y}`;grid.innerHTML='';let offset=(new Date(y,m,1).getDay()+6)%7,total=new Date(y,m+1,0).getDate();for(let i=0;i<offset;i++)grid.append(document.createElement('span'));for(let d=1;d<=total;d++){let date=new Date(y,m,d),b=document.createElement('button');b.type='button';b.textContent=d;b.disabled=date<new Date(today.getFullYear(),today.getMonth(),today.getDate())||date.getDay()===0;if(same(date,today))b.classList.add('today');if(same(date,state.date))b.classList.add('selected');b.addEventListener('click',()=>{state.date=date;state.time=null;renderCalendar();renderSlots();updateSummary();progress(2)});grid.append(b)}$('#prevMonth').disabled=y===today.getFullYear()&&m<=today.getMonth()}
function renderGroup(selector,list){let box=$(selector);box.innerHTML='';list.forEach((time,i)=>{let b=document.createElement('button');b.type='button';b.textContent=time;let now=new Date(),past=same(state.date,now)&&time<=`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`,busy=state.date&&(state.date.getDate()+i)%11===0;b.disabled=!state.date||past||busy;if(state.time===time)b.classList.add('selected');b.onclick=()=>{state.time=time;renderSlots();updateSummary();progress(2)};box.append(b)})}
function renderSlots(){renderGroup('#morningSlots',slots.morning);renderGroup('#afternoonSlots',slots.afternoon);$('#noDate').hidden=!!state.date;$('#chosenDateTitle').textContent=state.date?`${week[state.date.getDay()]}, ${state.date.getDate()} de ${months[state.date.getMonth()].toLowerCase()}`:'Selecione uma data'}
function updateSummary(){$('#summaryService').textContent=state.service.name;$('#summaryDescription').textContent=state.service.description;$('#summaryDuration').textContent=state.service.duration;$('#summaryPrice').textContent=money(state.service.price);$('#summaryDate').textContent=state.date?`${String(state.date.getDate()).padStart(2,'0')}/${String(state.date.getMonth()+1).padStart(2,'0')}/${state.date.getFullYear()}`:'A definir';$('#summaryTime').textContent=state.time||'A definir'}
function progress(step){$$('.progress-step').forEach((el,i)=>{el.classList.toggle('current',i+1===step);el.classList.toggle('done',i+1<step);el.querySelector('span').textContent=i+1<step?'✓':i+1})}
function toast(msg){let el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),4200)}
$$('.service-row').forEach(row=>row.onclick=()=>{$$('.service-row').forEach(x=>x.classList.remove('selected'));row.classList.add('selected');state.service={name:row.dataset.service,price:+row.dataset.price,duration:row.dataset.duration,description:row.dataset.description};updateSummary();progress(1)});
$('#prevMonth').onclick=()=>{let n=new Date(),p=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);if(p<new Date(n.getFullYear(),n.getMonth(),1))return;state.month=p;state.date=null;state.time=null;renderCalendar();renderSlots();updateSummary()};
$('#nextMonth').onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);state.date=null;state.time=null;renderCalendar();renderSlots();updateSummary()};
$('#clientPhone').addEventListener('input',e=>{let v=e.target.value.replace(/\D/g,'').slice(0,11);if(v.length>10)v=v.replace(/^(\d{2})(\d{5})(\d{4})$/,'($1) $2-$3');else if(v.length>6)v=v.replace(/^(\d{2})(\d{4})(\d{0,4})$/,'($1) $2-$3');else if(v.length>2)v=v.replace(/^(\d{2})(\d{0,5})$/,'($1) $2');else if(v)v=`(${v}`;e.target.value=v});
$('#confirmButton').onclick=()=>{if(!state.date)return toast('Selecione uma data no calendário.');if(!state.time)return toast('Escolha um dos horários disponíveis.');let name=$('#clientName').value.trim(),phone=$('#clientPhone').value.trim();if(name.length<2)return toast('Informe seu nome completo.');if(phone.replace(/\D/g,'').length<10)return toast('Confira seu número de WhatsApp.');let booking={service:state.service.name,price:state.service.price,duration:state.service.duration,date:`${state.date.getFullYear()}-${String(state.date.getMonth()+1).padStart(2,'0')}-${String(state.date.getDate()).padStart(2,'0')}`,time:state.time,name,phone,email:$('#clientEmail').value.trim(),notes:$('#clientNotes').value.trim(),createdAt:new Date().toISOString()};let all=JSON.parse(localStorage.getItem('irisBookings')||'[]');all.push(booking);localStorage.setItem('irisBookings',JSON.stringify(all));toast(`Solicitação registrada, ${name.split(' ')[0]}! Modo de demonstração.`);['#clientName','#clientPhone','#clientEmail','#clientNotes'].forEach(s=>$(s).value='');state.date=null;state.time=null;renderCalendar();renderSlots();updateSummary();progress(1)};
renderCalendar();renderSlots();updateSummary();